"""
ui/components/export_panel.py — Unified export / download panel.

Provides download buttons for:
  - Report as Markdown (.md)
  - Report as styled HTML (.html)  ← always available
  - Report as PDF (.pdf)           ← available if WeasyPrint works
  - Risk Scorecard JSON
  - Competitor Intel JSON
  - Full output bundle as ZIP

Usage on Research page (after pipeline run):
    from ui.components.export_panel import render_export_panel_from_state
    render_export_panel_from_state(final_state)

Usage on History page (from DB run):
    from ui.components.export_panel import render_export_panel_from_run
    render_export_panel_from_run(run)
"""

import io
import json
import zipfile
from datetime import datetime
from pathlib import Path
from typing import Optional

import streamlit as st


def _get_sector_label(seed_data: dict) -> str:
    """Helper to get sector label from seed data."""
    try:
        from prompts.sectors import detect_sector, get_sector_label
        return get_sector_label(detect_sector(seed_data))
    except Exception:
        return "Technology"


def _build_zip(
    company_slug:    str,
    report_markdown: str,
    html_bytes:      Optional[bytes],
    pdf_bytes:       Optional[bytes],
    risk_scorecard:  dict,
    competitor_data: dict,
    investor_data:   dict,
    team_data:       dict,
) -> bytes:
    """Build a ZIP archive of all report artifacts."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # Report files
        zf.writestr(f"{company_slug}_report.md", report_markdown.encode("utf-8"))
        if html_bytes:
            zf.writestr(f"{company_slug}_report.html", html_bytes)
        if pdf_bytes:
            zf.writestr(f"{company_slug}_report.pdf", pdf_bytes)

        # JSON artifacts
        artifacts = {
            "risk_scorecard.json":  risk_scorecard,
            "competitor_intel.json": competitor_data,
            "investors.json":        investor_data,
            "founders_team.json":    team_data,
        }
        for filename, data in artifacts.items():
            if data:
                zf.writestr(
                    f"{company_slug}_{filename}",
                    json.dumps(data, indent=2).encode("utf-8"),
                )

        # Readme
        readme = f"""# IntelliDD Pro — {company_slug.title()} Due Diligence Package

Generated: {datetime.now().strftime('%B %d, %Y')}

## Contents
- {company_slug}_report.md        — Full due diligence report (Markdown)
- {company_slug}_report.html      — Styled HTML report (open in browser, print to PDF)
- {company_slug}_report.pdf       — PDF report (if WeasyPrint was available)
- {company_slug}_risk_scorecard.json   — Quantitative risk scores
- {company_slug}_competitor_intel.json — Competitor analysis
- {company_slug}_investors.json        — Funding and investor data
- {company_slug}_founders_team.json    — Team and leadership data

## Generated By
IntelliDD Pro — AI-Powered Multi-Agent Due Diligence Platform
https://github.com/yourusername/intellidd-pro
"""
        zf.writestr("README.md", readme.encode("utf-8"))

    return buf.getvalue()


def _render_export_buttons(
    company_slug:    str,
    company_name:    str,
    report_markdown: str,
    risk_scorecard:  dict,
    competitor_data: dict,
    investor_data:   dict,
    team_data:       dict,
    seed_data:       dict,
    run_id:          str,
    output_dir:      str = "./outputs",
) -> None:
    """Internal: render all export buttons given extracted data."""

    # Generate HTML and attempt PDF on demand
    if st.button(
        "📄 Generate PDF Report",
        type="primary",
        key=f"gen_pdf_{run_id}",
        use_container_width=True,
        help="Converts the report to a professionally styled PDF document",
    ):
        with st.spinner("Generating PDF..."):
            try:
                from utils.pdf_exporter import export_report

                sector_label = _get_sector_label(seed_data)
                company_url  = seed_data.get("website", "")
                run_date     = datetime.now().strftime("%B %d, %Y")

                result = export_report(
                    report_markdown=report_markdown,
                    company_name=company_name,
                    company_url=company_url,
                    sector_label=sector_label,
                    risk_scorecard=risk_scorecard,
                    run_id=run_id,
                    output_dir=output_dir,
                    run_date=run_date,
                )
                st.session_state[f"export_{run_id}"] = result
                st.rerun()
            except Exception as e:
                st.error(f"Export failed: {e}")

    # Show download buttons if export was generated
    export = st.session_state.get(f"export_{run_id}", {})
    html_bytes = export.get("html_bytes")
    pdf_bytes  = export.get("pdf_bytes")

    # Generate HTML bytes directly if not yet exported
    if not html_bytes and report_markdown:
        try:
            from utils.pdf_exporter import build_report_html
            html_content = build_report_html(
                report_markdown=report_markdown,
                company_name=company_name,
                company_url=seed_data.get("website", ""),
                sector_label=_get_sector_label(seed_data),
                risk_scorecard=risk_scorecard,
                run_id=run_id,
            )
            html_bytes = html_content.encode("utf-8")
        except Exception:
            html_bytes = report_markdown.encode("utf-8")

    st.markdown("<br/>", unsafe_allow_html=True)

    # Row 1: Report downloads
    st.markdown("**📄 Report**")
    r1c1, r1c2, r1c3 = st.columns(3)

    with r1c1:
        st.download_button(
            "⬇ Markdown",
            data=report_markdown,
            file_name=f"{company_slug}_report.md",
            mime="text/markdown",
            use_container_width=True,
            key=f"dl_md_{run_id}",
        )

    with r1c2:
        if html_bytes:
            st.download_button(
                "⬇ HTML Report",
                data=html_bytes,
                file_name=f"{company_slug}_report.html",
                mime="text/html",
                use_container_width=True,
                key=f"dl_html_{run_id}",
            )
        else:
            st.button("⬇ HTML", disabled=True,
                      use_container_width=True, key=f"dl_html_d_{run_id}")

    with r1c3:
        if pdf_bytes:
            st.download_button(
                "⬇ PDF Report",
                data=pdf_bytes,
                file_name=f"{company_slug}_report.pdf",
                mime="application/pdf",
                use_container_width=True,
                key=f"dl_pdf_{run_id}",
            )
        else:
            pdf_note = "WeasyPrint not available" if export else "Click Generate PDF first"
            st.button(
                f"⬇ PDF ({pdf_note})",
                disabled=True,
                use_container_width=True,
                key=f"dl_pdf_d_{run_id}",
            )

    st.markdown("<br/>", unsafe_allow_html=True)

    # Row 2: JSON artifacts
    st.markdown("**📊 Data Artifacts**")
    r2c1, r2c2, r2c3 = st.columns(3)

    with r2c1:
        if risk_scorecard:
            st.download_button(
                "⬇ Risk Scorecard",
                data=json.dumps(risk_scorecard, indent=2),
                file_name=f"{company_slug}_risk_scorecard.json",
                mime="application/json",
                use_container_width=True,
                key=f"dl_risk_{run_id}",
            )

    with r2c2:
        if competitor_data:
            st.download_button(
                "⬇ Competitor Intel",
                data=json.dumps(competitor_data, indent=2),
                file_name=f"{company_slug}_competitors.json",
                mime="application/json",
                use_container_width=True,
                key=f"dl_comp_{run_id}",
            )

    with r2c3:
        if investor_data:
            st.download_button(
                "⬇ Investor Data",
                data=json.dumps(investor_data, indent=2),
                file_name=f"{company_slug}_investors.json",
                mime="application/json",
                use_container_width=True,
                key=f"dl_inv_{run_id}",
            )

    st.markdown("<br/>", unsafe_allow_html=True)

    # Row 3: Full ZIP bundle
    st.markdown("**📦 Full Package**")
    try:
        zip_bytes = _build_zip(
            company_slug=company_slug,
            report_markdown=report_markdown,
            html_bytes=html_bytes,
            pdf_bytes=pdf_bytes,
            risk_scorecard=risk_scorecard,
            competitor_data=competitor_data,
            investor_data=investor_data,
            team_data=team_data,
        )
        st.download_button(
            f"⬇ Download Complete Package ({len(zip_bytes)//1024:,} KB ZIP)",
            data=zip_bytes,
            file_name=f"{company_slug}_intellidd_package.zip",
            mime="application/zip",
            use_container_width=True,
            key=f"dl_zip_{run_id}",
            type="primary",
        )
    except Exception as e:
        st.warning(f"ZIP build failed: {e}")

    # WeasyPrint install note
    if not pdf_bytes and export:
        st.caption(
            "💡 For PDF export on Windows: install GTK3 Runtime from "
            "https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer "
            "then restart the app. The HTML report is fully printable as PDF "
            "from any browser (File → Print → Save as PDF)."
        )


def render_export_panel_from_state(final_state: dict) -> None:
    """
    Render the export panel from a DDState final_state dict.
    Use this on the main Research page immediately after a pipeline run.
    """
    seed_data    = final_state.get("seed_data", {})
    company_name = seed_data.get("company_name", "Company")
    company_url  = final_state.get("company_url", "")
    company_slug = (
        company_url.replace("https://", "").replace("http://", "")
        .replace("www.", "").split("/")[0].split(".")[0].lower()
    )
    run_id     = final_state.get("run_id", "unknown")
    output_dir = final_state.get("output_dir", "./outputs")

    _render_export_buttons(
        company_slug=company_slug,
        company_name=company_name,
        report_markdown=final_state.get("report_markdown", ""),
        risk_scorecard=final_state.get("risk_scorecard", {}),
        competitor_data=final_state.get("competitor_data", {}),
        investor_data=final_state.get("investor_data", {}),
        team_data=final_state.get("team_data", {}),
        seed_data=seed_data,
        run_id=run_id,
        output_dir=output_dir,
    )


def render_export_panel_from_run(run) -> None:
    """
    Render the export panel from a ResearchRun DB object.
    Use this on the History page.
    """
    _render_export_buttons(
        company_slug=run.company_slug,
        company_name=run.company_name,
        report_markdown=run.report_markdown,
        risk_scorecard=run.risk_scorecard,
        competitor_data=run.competitor_data,
        investor_data=run.investor_data,
        team_data=run.team_data,
        seed_data=run.seed_data,
        run_id=run.run_id,
        output_dir=run.output_dir or "./outputs",
    )